[cargo-compete]
src.git = "https://github.com/qryxip/cargo-compete.git"
fetch.github = "qryxip/cargo-compete"
cargo_locks = ["Cargo.lock"]

[testing-language-server]
src.git = "https://github.com/kbwo/testing-language-server.git"
fetch.github = "kbwo/testing-language-server"
cargo_locks = ["Cargo.lock"]
