# https://taskfile.dev
version: "3"
tasks:
  switch:
    cmds:
      - sudo nixos-rebuild switch --flake ~/dotfiles
  setup-ocaml:
    cmds:
      - elan default stable
      - opam init && opam install ocaml-lsp-server odoc ocamlformat utop dune
  installer:
    cmds:
      - nix build .#nixosConfigurations.installer.config.system.build.isoImage
