# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  typst-preview = {
    pname = "typst-preview";
    version = "4f3decb8d9b85b1a06b0dfbd0fccaa0d2d2c24b4";
    src = fetchFromGitHub {
      owner = "havarddj";
      repo = "typst-preview.el";
      rev = "4f3decb8d9b85b1a06b0dfbd0fccaa0d2d2c24b4";
      fetchSubmodules = false;
      sha256 = "sha256-rxXgIoILnxyn543keCkpuv80TLaSATN1T7hCvnM8inU=";
    };
    date = "2025-08-12";
  };
  typst-ts-mode = {
    pname = "typst-ts-mode";
    version = "1367003e2ad55a2f6f9e43178584683028ab56e9";
    src = fetchgit {
      url = "https://git.sr.ht/~meow_king/typst-ts-mode";
      rev = "1367003e2ad55a2f6f9e43178584683028ab56e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0RAJ/Td3G7FDvzf7t8csNs/uc07WUPGvMo8ako5iyl0=";
    };
    date = "2024-12-07";
  };
  yazi-compress = {
    pname = "yazi-compress";
    version = "c2646395394f22b6c40bff64dc4c8c922d210570";
    src = fetchFromGitHub {
      owner = "KKV9";
      repo = "compress.yazi";
      rev = "c2646395394f22b6c40bff64dc4c8c922d210570";
      fetchSubmodules = false;
      sha256 = "sha256-qAuMD4YojLfVaywurk5uHLywRRF77U2F7ql+gR8B/lo=";
    };
    date = "2025-08-15";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "2301ff803a033cd16d16e62697474d6cb9a94711";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "2301ff803a033cd16d16e62697474d6cb9a94711";
      fetchSubmodules = false;
      sha256 = "sha256-+lirIBXv3EvztE/1b3zHnQ9r5N3VWBCUuH3gZR52fE0=";
    };
    date = "2025-11-19";
  };
}
