# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  typst-preview = {
    pname = "typst-preview";
    version = "4f3decb8d9b85b1a06b0dfbd0fccaa0d2d2c24b4";
    src = fetchFromGitHub {
      owner = "havarddj";
      repo = "typst-preview.el";
      rev = "4f3decb8d9b85b1a06b0dfbd0fccaa0d2d2c24b4";
      fetchSubmodules = false;
      sha256 = "sha256-rxXgIoILnxyn543keCkpuv80TLaSATN1T7hCvnM8inU=";
    };
    date = "2025-08-12";
  };
  typst-ts-mode = {
    pname = "typst-ts-mode";
    version = "1367003e2ad55a2f6f9e43178584683028ab56e9";
    src = fetchgit {
      url = "https://git.sr.ht/~meow_king/typst-ts-mode";
      rev = "1367003e2ad55a2f6f9e43178584683028ab56e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0RAJ/Td3G7FDvzf7t8csNs/uc07WUPGvMo8ako5iyl0=";
    };
    date = "2024-12-07";
  };
  yazi-compress = {
    pname = "yazi-compress";
    version = "cb6e8ec0141915dc319ccd6b904dcd2f03502576";
    src = fetchFromGitHub {
      owner = "KKV9";
      repo = "compress.yazi";
      rev = "cb6e8ec0141915dc319ccd6b904dcd2f03502576";
      fetchSubmodules = false;
      sha256 = "sha256-D/EpcRDIc3toeyjHqi+vGw0v9B22HVvKJua5EVEAc0U=";
    };
    date = "2026-01-24";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "88990a6cf1d31afd9d8db1a0d74bf37ef50d6786";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "88990a6cf1d31afd9d8db1a0d74bf37ef50d6786";
      fetchSubmodules = false;
      sha256 = "sha256-0K6qGgbGt8N6HgGNEmn2FDLar6hCPiPBbvOsrTjSubM=";
    };
    date = "2026-02-06";
  };
}
