name: build and cache
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '**/*.nix'
      - 'flake.lock'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Build
        run: nix build --flake .#desktop
