name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '**/*.nix'
      - 'flake.lock'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Nix Flake
        run: |
          nix-shell -p '(nixos{}).nixos-rebuild' --run nixos-rebuild --extra-experimental-features 'nix-command flakes' .#desktop
