name: Check nix configs
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '**/*.nix'
      - 'flake.lock'
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
  check-lock:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5
      - name: Check the flake
        uses: DeterminateSystems/flake-checker-action@main
      - name: actions-cloc
        uses: maxfie1d/actions-cloc@v1
  check-expr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        host:
          - desktop
    steps:
      - uses: actions/checkout@v5
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - run: nix flake check
